# Generated by Django 2.0 on 2019-11-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gridapp', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
